---
- hosts: nexus
  vars_files:
   - file-for-variables.yml
  tasks:
   - name: Display dictionary value
     debug: 
       msg: "{{ myList[0] }}"

   - name: Display dictionary key  value
     debug:
       msg: "{{ myList[1] }}"

   - name: Display dictionary key  value
     debug:
       msg: "{{ myList[2] }}"

...
