---
- hosts: nexus
  dict:
    myList: [ 
     "mykey1" : my value1
     "mykey2" : my value2
     "mykey3" : my value3
     ]
  tasks:
   - name: Display dictionary value
     debug: 
       msg: "{{ myList[0] }}"

   - name: Display dictionary key  value
     debug:
       msg: "{{ myList[1] }}"

   - name: Display dictionary key  value
     debug:
       msg: "{{ myList[2] }}"

...
