---
# tasks file for tomcat
#

  - name: Install Apache2 on Ubuntu
    package: name=apache2 state=latest
    when: ansible_distribution == "Ubuntu"
    tags: install-on-ubuntu

  - name: Install Httpd on CentOS
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: Copy template
    template:
      src: index.html
      dest: /var/www/html/index.html
      mode: 0777

  - name: Disable firewall cmd on CentOS
    shell: |
      systemctl disable firewalld
      systemctl stop firewalld
    when: ansible_os_family == "RedHat"

  - name: Enable Httpd on CentOS
    shell: |
      systemctl enable httpd
      systemctl start httpd
    when: ansible_os_family == "RedHat"    

  - name: Enable Apache2 on CentOS
    shell: |
      systemctl enable apache2
      systemctl start apache2
    when: ansible_distribution == "Ubuntu"
  
  - name: Findout Uptime
    command: uptime
    register: uptime
    tags: tellme-uptime

  - debug:
      msg: Welcome to the {{ item }} system uptime for {{ item }} server {{ ansible_nodename }} is {{ uptime.stdout }}
    with_items: [ 'CentOS' , 'Ubuntu' ]
    when: ansible_distribution == item
    tags: tellme-uptime
